# runtime/config.yaml

# 基础配置
debug: true
role: "user"         
node_id: "user-001"

# 模型加载配置
base_model: "/workspace/deepseek-math-7b-instruct"
sys_prompt: "Please solve the subtask and output the final result strictly within the \\Answer{} tag. Do not add any extra text, explanations, or formatting outside of this tag."
load_quantized: true
use_lora: true

# 能力注册（自动与工具匹配）
capabilities:
  - math
  - translation
  - search

# 网络参数
p2p:
  port: 7788
  enable_dht: true
  beacon_ttl: 2
  heartbeat_interval: 15

# LoRA 存储
lora:
  save_dir: "checkpoints/"
  patch_interval: 300

# 日志
log_level: "INFO"

# 网络适配器配置
network:
  host: "127.0.0.1"  # 替换为 TaskRequester 服务器的 IP 地址
  port: 4000

# GPU 配置
gpu_id: 0  # 假设服务器有4个GPU卡

# neighbours
neighbours: [["agent-001", "127.0.0.1", 5000],
             ["agent-002", "127.0.0.1", 6000],
             ["agent-003", "127.0.0.1", 7000]]